import Banner from "../pages/banner/Banner";
import PhotoGallery from "../pages/photoGallery/PhotoGallery";

const Home = () => {
    return (
        <div className="bg-white z-20 ">
            <img src="https://demo.ishithemes.com/shopify/SHOPY126/asset/img/cloud.png" className="-translate-y-full" />

            <PhotoGallery />
            g
            <h1>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Odit ratione sequi ex fuga eligendi doloremque non illum fugiat eveniet voluptatum corporis minima incidunt, maiores necessitatibus, inventore repellendus dolor sint architecto optio nostrum totam magni ut. Blanditiis ut laborum odit et unde at ad ab, eius tempora corporis repellendus consequuntur voluptatum itaque neque quis repudiandae necessitatibus? Molestiae, corporis cumque quasi suscipit ipsa doloremque. Eum ducimus porro error saepe facere modi praesentium obcaecati eveniet quam deleniti debitis quos, recusandae tempora maxime, perspiciatis esse et possimus nisi eligendi fugit iusto? Dicta id facere beatae cumque minus velit autem, tempora, doloribus temporibus, ratione quo!</h1>
            <h1>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Odit ratione sequi ex fuga eligendi doloremque non illum fugiat eveniet voluptatum corporis minima incidunt, maiores necessitatibus, inventore repellendus dolor sint architecto optio nostrum totam magni ut. Blanditiis ut laborum odit et unde at ad ab, eius tempora corporis repellendus consequuntur voluptatum itaque neque quis repudiandae necessitatibus? Molestiae, corporis cumque quasi suscipit ipsa doloremque. Eum ducimus porro error saepe facere modi praesentium obcaecati eveniet quam deleniti debitis quos, recusandae tempora maxime, perspiciatis esse et possimus nisi eligendi fugit iusto? Dicta id facere beatae cumque minus velit autem, tempora, doloribus temporibus, ratione quo!</h1>
            <h1>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Odit ratione sequi ex fuga eligendi doloremque non illum fugiat eveniet voluptatum corporis minima incidunt, maiores necessitatibus, inventore repellendus dolor sint architecto optio nostrum totam magni ut. Blanditiis ut laborum odit et unde at ad ab, eius tempora corporis repellendus consequuntur voluptatum itaque neque quis repudiandae necessitatibus? Molestiae, corporis cumque quasi suscipit ipsa doloremque. Eum ducimus porro error saepe facere modi praesentium obcaecati eveniet quam deleniti debitis quos, recusandae tempora maxime, perspiciatis esse et possimus nisi eligendi fugit iusto? Dicta id facere beatae cumque minus velit autem, tempora, doloribus temporibus, ratione quo!</h1>
            <h1>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Odit ratione sequi ex fuga eligendi doloremque non illum fugiat eveniet voluptatum corporis minima incidunt, maiores necessitatibus, inventore repellendus dolor sint architecto optio nostrum totam magni ut. Blanditiis ut laborum odit et unde at ad ab, eius tempora corporis repellendus consequuntur voluptatum itaque neque quis repudiandae necessitatibus? Molestiae, corporis cumque quasi suscipit ipsa doloremque. Eum ducimus porro error saepe facere modi praesentium obcaecati eveniet quam deleniti debitis quos, recusandae tempora maxime, perspiciatis esse et possimus nisi eligendi fugit iusto? Dicta id facere beatae cumque minus velit autem, tempora, doloribus temporibus, ratione quo!</h1>
            <h1>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Odit ratione sequi ex fuga eligendi doloremque non illum fugiat eveniet voluptatum corporis minima incidunt, maiores necessitatibus, inventore repellendus dolor sint architecto optio nostrum totam magni ut. Blanditiis ut laborum odit et unde at ad ab, eius tempora corporis repellendus consequuntur voluptatum itaque neque quis repudiandae necessitatibus? Molestiae, corporis cumque quasi suscipit ipsa doloremque. Eum ducimus porro error saepe facere modi praesentium obcaecati eveniet quam deleniti debitis quos, recusandae tempora maxime, perspiciatis esse et possimus nisi eligendi fugit iusto? Dicta id facere beatae cumque minus velit autem, tempora, doloribus temporibus, ratione quo!</h1>
            <h1>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Odit ratione sequi ex fuga eligendi doloremque non illum fugiat eveniet voluptatum corporis minima incidunt, maiores necessitatibus, inventore repellendus dolor sint architecto optio nostrum totam magni ut. Blanditiis ut laborum odit et unde at ad ab, eius tempora corporis repellendus consequuntur voluptatum itaque neque quis repudiandae necessitatibus? Molestiae, corporis cumque quasi suscipit ipsa doloremque. Eum ducimus porro error saepe facere modi praesentium obcaecati eveniet quam deleniti debitis quos, recusandae tempora maxime, perspiciatis esse et possimus nisi eligendi fugit iusto? Dicta id facere beatae cumque minus velit autem, tempora, doloribus temporibus, ratione quo!</h1>
            <h1>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Odit ratione sequi ex fuga eligendi doloremque non illum fugiat eveniet voluptatum corporis minima incidunt, maiores necessitatibus, inventore repellendus dolor sint architecto optio nostrum totam magni ut. Blanditiis ut laborum odit et unde at ad ab, eius tempora corporis repellendus consequuntur voluptatum itaque neque quis repudiandae necessitatibus? Molestiae, corporis cumque quasi suscipit ipsa doloremque. Eum ducimus porro error saepe facere modi praesentium obcaecati eveniet quam deleniti debitis quos, recusandae tempora maxime, perspiciatis esse et possimus nisi eligendi fugit iusto? Dicta id facere beatae cumque minus velit autem, tempora, doloribus temporibus, ratione quo!</h1>
            <h1>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Odit ratione sequi ex fuga eligendi doloremque non illum fugiat eveniet voluptatum corporis minima incidunt, maiores necessitatibus, inventore repellendus dolor sint architecto optio nostrum totam magni ut. Blanditiis ut laborum odit et unde at ad ab, eius tempora corporis repellendus consequuntur voluptatum itaque neque quis repudiandae necessitatibus? Molestiae, corporis cumque quasi suscipit ipsa doloremque. Eum ducimus porro error saepe facere modi praesentium obcaecati eveniet quam deleniti debitis quos, recusandae tempora maxime, perspiciatis esse et possimus nisi eligendi fugit iusto? Dicta id facere beatae cumque minus velit autem, tempora, doloribus temporibus, ratione quo!</h1>
            <h1>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Odit ratione sequi ex fuga eligendi doloremque non illum fugiat eveniet voluptatum corporis minima incidunt, maiores necessitatibus, inventore repellendus dolor sint architecto optio nostrum totam magni ut. Blanditiis ut laborum odit et unde at ad ab, eius tempora corporis repellendus consequuntur voluptatum itaque neque quis repudiandae necessitatibus? Molestiae, corporis cumque quasi suscipit ipsa doloremque. Eum ducimus porro error saepe facere modi praesentium obcaecati eveniet quam deleniti debitis quos, recusandae tempora maxime, perspiciatis esse et possimus nisi eligendi fugit iusto? Dicta id facere beatae cumque minus velit autem, tempora, doloribus temporibus, ratione quo!</h1>
        </div>
    );
};

export default Home;